name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - ujson
  - numpy
  - pip
  - spacy=2.0.16
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pip:
    - torch==1.10.2+cu113
