name: squad
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.11
  - ujson
  - numpy
  - pip
  - spacy
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pytorch
  - pytorch-cuda=12.1
